export class APP_LANG {
  static get Constants(): any {
    return {
      ENGLISH: {
        EMAIL: 'Email',
        PASSWORD: 'Password',
        LOG_IN: 'Log in',
        FORGOT_PASSWORD: 'Forgot your Password',
        WELCOME_TO: 'Welcome to',
        NAME: 'Name',
        MOBILE_PHONE: 'Mobile Phone',
        LOGOUT: 'Logout',
        VALID_EMAIL: 'Please enter a valid email',
        VALID_PASSWORD: 'Password needs more than 6 characters',
        BACK: 'Back',
        YOUR_EMAIL: 'Your email address',
        RESET_PASSWORD: 'Reset your password',
        LOGGED_OUT: 'You are now logged out',
        LAST_NAME: 'Last Name',
        SAVE: 'Save',
        PROFILE: 'Profile',
        POSITION: 'Position',
        COUNTRY: 'Country',
        CITY: 'City',
        BIRTHDAY: 'Birthday',
        SEX: 'Sex',
        CONTACT: 'CONCTACT',
        EDIT_PROFILE: 'Edit Profile',
        HI: 'Hi',
        LAST_CONNECTION: 'Last connection',
        VISITED_ESTABLISHMENT: 'Visited establishments',
        ESTABLISHMENT_BY_SINCRONIZE: 'Establishments by sincronize',
        TOTAL_FORMS_BY_FILL: 'Total forms by Fill',
        TOTAL_FORMS_BY_SINCRONIZE: 'Total forms by sincronize',
        TOTAL_SAVED_FORMS: 'Total saved forms',
        FORM_AVERAGE_TIME: 'Forms average time',
      },
      SPANISH: {
        EMAIL: 'Email',
        PASSWORD: 'Contraseña',
        LOG_IN: 'Iniciar sesión',
        FORGOT_PASSWORD: 'Olvidaste tu contraseña',
        WELCOME_TO: 'Bienvenido a',
        NAME: 'Nombre',
        MOBILE_PHONE: 'Telefono Movil',
        LOGOUT: 'Cerrar sesión',
        VALID_EMAIL: 'Por favor introduce un email valido',
        VALID_PASSWORD: 'La contraseña necesita más de 6 caracteres',
        BACK: 'Atras',
        YOUR_EMAIL: 'Tu dirección de email',
        RESET_PASSWORD: 'Reestablece tu contraseña',
        LOGGED_OUT: 'Estas ahora deslogeado',
        LAST_NAME: 'Apellido',
        SAVE: 'Guardar',
        PROFILE: 'Perfil',
        POSITION: 'Cargo',
        COUNTRY: 'Pais',
        CITY: 'Ciudad',
        BIRTHDAY: 'Fecha Nacimiento',
        SEX: 'Sexo',
        CONTACT: 'Contacto',
        EDIT_PROFILE: 'Editar Perfil',
        HI: 'Hola',
        LAST_CONNECTION: 'Ultima conexión',
        VISITED_ESTABLISHMENT: 'Establecimientos visitados',
        ESTABLISHMENT_BY_SINCRONIZE: 'Establecimientos por sincronizar',
        TOTAL_FORMS_BY_FILL: 'Total formularios por llenar',
        TOTAL_FORMS_BY_SINCRONIZE: 'Total formularios por sincronizar',
        TOTAL_SAVED_FORMS: 'Total formularios guardados',
        FORM_AVERAGE_TIME: 'Tiempo promedio formulario',
      },
      FRENCH: {

      }
    }
  }
}